// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kldubyxchpjaitdmkwob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtsZHVieXhjaHBqYWl0ZG1rd29iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NjAxMjYsImV4cCI6MjA2NDAzNjEyNn0.LeRSWzwk3ZI6lOaU5vM7o7UyInK1UCx3PU4_4gkxDTs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);